//! The account key and how it travels.
//!
//! The account key (AK) is 32 random bytes generated by the first device.
//! Every other key used for content derives from it, so devices that hold AK
//! can read and write the account and nobody else can.
//!
//! The server stores AK wrapped under a key that takes two things to
//! compute: the OPAQUE `export_key`, which needs the password, and the
//! [`AccountSecret`], which only the account's devices have and hand to a new
//! device when someone approves it (see [`crate::approval`]). The password
//! alone opens nothing, and neither does anything the server has.

use zeroize::Zeroizing;

use crate::wire::Reader;
use crate::{Error, Id, Rng, aead_open, aead_seal, derive_key, transcript};

/// The account key at a given epoch. The epoch starts at 1 and increases
/// every time the key is rotated (to cut off a revoked device).
pub struct AccountKey {
    epoch: u32,
    key: Zeroizing<[u8; 32]>,
}

impl AccountKey {
    pub fn generate(rng: &mut impl Rng) -> Self {
        let mut key = Zeroizing::new([0u8; 32]);
        rng.fill_bytes(key.as_mut());
        Self { epoch: 1, key }
    }

    /// The next key, for rotation.
    pub fn rotate(&self, rng: &mut impl Rng) -> Self {
        let mut next = Self::generate(rng);
        next.epoch = self
            .epoch
            .checked_add(1)
            .expect("account key epoch overflow");
        next
    }

    /// A key loaded from the OS keychain. Epochs start at 1.
    pub fn from_bytes(epoch: u32, key: [u8; 32]) -> Result<Self, Error> {
        if epoch == 0 {
            return Err(Error::Malformed("account key epoch"));
        }
        Ok(Self {
            epoch,
            key: Zeroizing::new(key),
        })
    }

    pub fn epoch(&self) -> u32 {
        self.epoch
    }

    /// The raw key, for storing in the OS keychain. Never send it anywhere.
    pub fn expose_secret(&self) -> &[u8; 32] {
        &self.key
    }

    /// A fingerprint of the account key, safe to show: a subkey of its own,
    /// so it reveals nothing about the key or the other subkeys. Every device
    /// of the account shows the same one; the server can't compute it.
    pub fn fingerprint(&self) -> [u8; 16] {
        let subkey = self.subkey("fingerprint");
        let mut fingerprint = [0u8; 16];
        fingerprint.copy_from_slice(&subkey[..16]);
        fingerprint
    }

    pub(crate) fn items_key(&self) -> Zeroizing<[u8; 32]> {
        self.subkey("items")
    }

    pub(crate) fn devices_key(&self) -> Zeroizing<[u8; 32]> {
        self.subkey("devices")
    }

    fn subkey(&self, purpose: &str) -> Zeroizing<[u8; 32]> {
        derive_key(
            self.key.as_ref(),
            &transcript(
                "pastazzo/v1/subkey",
                &[purpose.as_bytes(), &self.epoch.to_be_bytes()],
            ),
        )
    }
}

/// The second thing it takes to open the wrapped account key, next to the
/// password. 32 random bytes made by the first device and passed from device
/// to device, never to the server.
pub struct AccountSecret(Zeroizing<[u8; 32]>);

impl AccountSecret {
    pub fn generate(rng: &mut impl Rng) -> Self {
        let mut secret = Zeroizing::new([0u8; 32]);
        rng.fill_bytes(secret.as_mut());
        Self(secret)
    }

    pub fn from_bytes(secret: [u8; 32]) -> Self {
        Self(Zeroizing::new(secret))
    }

    /// The raw secret, for the OS keychain and for sealing to a new device.
    pub fn expose_secret(&self) -> &[u8; 32] {
        &self.0
    }
}

/// AK encrypted under a key derived from the OPAQUE `export_key` and the
/// [`AccountSecret`].
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct WrappedAccountKey {
    pub epoch: u32,
    pub nonce: [u8; 24],
    pub ciphertext: Vec<u8>,
}

impl WrappedAccountKey {
    pub fn wrap(
        key: &AccountKey,
        export_key: &[u8],
        secret: &AccountSecret,
        account: &Id,
        rng: &mut impl Rng,
    ) -> Self {
        let (nonce, ciphertext) = aead_seal(
            &wrapping_key(export_key, secret),
            key.key.as_ref(),
            &wrap_aad(account, key.epoch),
            rng,
        );
        Self {
            epoch: key.epoch,
            nonce,
            ciphertext,
        }
    }

    pub fn unwrap(
        &self,
        export_key: &[u8],
        secret: &AccountSecret,
        account: &Id,
    ) -> Result<AccountKey, Error> {
        let plaintext = Zeroizing::new(aead_open(
            &wrapping_key(export_key, secret),
            &self.nonce,
            &self.ciphertext,
            &wrap_aad(account, self.epoch),
        )?);
        if plaintext.len() != 32 {
            return Err(Error::Malformed("account key"));
        }
        let mut key = Zeroizing::new([0u8; 32]);
        key.copy_from_slice(&plaintext);
        Ok(AccountKey {
            epoch: self.epoch,
            key,
        })
    }

    /// `u32be(epoch) || nonce(24) || ciphertext(48)`
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut out = Vec::with_capacity(4 + 24 + self.ciphertext.len());
        out.extend_from_slice(&self.epoch.to_be_bytes());
        out.extend_from_slice(&self.nonce);
        out.extend_from_slice(&self.ciphertext);
        out
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<Self, Error> {
        let mut reader = Reader::new(bytes, "wrapped account key");
        let epoch = reader.u32()?;
        let nonce = reader.array()?;
        let ciphertext = reader.rest().to_vec();
        if epoch == 0 || ciphertext.len() != 32 + 16 {
            return Err(Error::Malformed("wrapped account key"));
        }
        Ok(Self {
            epoch,
            nonce,
            ciphertext,
        })
    }

    #[cfg(test)]
    pub(crate) fn wrap_with_nonce(
        key: &AccountKey,
        export_key: &[u8],
        secret: &AccountSecret,
        account: &Id,
        nonce: [u8; 24],
    ) -> Self {
        let ciphertext = crate::aead_seal_with_nonce(
            &wrapping_key(export_key, secret),
            &nonce,
            key.key.as_ref(),
            &wrap_aad(account, key.epoch),
        );
        Self {
            epoch: key.epoch,
            nonce,
            ciphertext,
        }
    }
}

fn wrapping_key(export_key: &[u8], secret: &AccountSecret) -> Zeroizing<[u8; 32]> {
    let mut ikm = Zeroizing::new(Vec::with_capacity(export_key.len() + 32));
    ikm.extend_from_slice(export_key);
    ikm.extend_from_slice(secret.expose_secret());
    derive_key(&ikm, &transcript("pastazzo/v1/wrapping-key", &[]))
}

fn wrap_aad(account: &Id, epoch: u32) -> Vec<u8> {
    transcript(
        "pastazzo/v1/wrapped-account-key",
        &[account, &epoch.to_be_bytes()],
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand::rngs::OsRng;

    fn secret() -> AccountSecret {
        AccountSecret::from_bytes([5u8; 32])
    }

    #[test]
    fn the_password_alone_opens_nothing() {
        let key = AccountKey::generate(&mut OsRng);
        let wrapped = WrappedAccountKey::wrap(&key, &[9u8; 64], &secret(), &[1u8; 16], &mut OsRng);
        let other = AccountSecret::from_bytes([6u8; 32]);
        assert_eq!(
            wrapped.unwrap(&[9u8; 64], &other, &[1u8; 16]).err(),
            Some(Error::Decrypt)
        );
        assert!(wrapped.unwrap(&[9u8; 64], &secret(), &[1u8; 16]).is_ok());
    }

    #[test]
    fn wrap_roundtrip() {
        let key = AccountKey::generate(&mut OsRng);
        let export_key = [9u8; 64];
        let account = [1u8; 16];
        let wrapped = WrappedAccountKey::wrap(&key, &export_key, &secret(), &account, &mut OsRng);
        let decoded = WrappedAccountKey::from_bytes(&wrapped.to_bytes()).unwrap();
        assert_eq!(decoded, wrapped);
        let unwrapped = decoded.unwrap(&export_key, &secret(), &account).unwrap();
        assert_eq!(unwrapped.expose_secret(), key.expose_secret());
        assert_eq!(unwrapped.epoch(), 1);
    }

    #[test]
    fn wrong_password_account_or_epoch_fails() {
        let key = AccountKey::generate(&mut OsRng);
        let wrapped = WrappedAccountKey::wrap(&key, &[9u8; 64], &secret(), &[1u8; 16], &mut OsRng);
        assert_eq!(
            wrapped.unwrap(&[8u8; 64], &secret(), &[1u8; 16]).err(),
            Some(Error::Decrypt)
        );
        assert_eq!(
            wrapped.unwrap(&[9u8; 64], &secret(), &[2u8; 16]).err(),
            Some(Error::Decrypt)
        );
        let mut bumped = wrapped.clone();
        bumped.epoch = 2;
        assert_eq!(
            bumped.unwrap(&[9u8; 64], &secret(), &[1u8; 16]).err(),
            Some(Error::Decrypt)
        );
    }

    #[test]
    fn subkeys_depend_on_purpose_and_epoch() {
        let key = AccountKey::from_bytes(1, [3u8; 32]).unwrap();
        assert!(AccountKey::from_bytes(0, [3u8; 32]).is_err());
        assert_ne!(*key.items_key(), *key.devices_key());
        let next = AccountKey::from_bytes(2, [3u8; 32]).unwrap();
        assert_ne!(*key.items_key(), *next.items_key());
    }

    #[test]
    fn fingerprint_is_stable_and_per_key() {
        let key = AccountKey::from_bytes(1, [3u8; 32]).unwrap();
        assert_eq!(
            key.fingerprint(),
            AccountKey::from_bytes(1, [3u8; 32]).unwrap().fingerprint()
        );
        assert_ne!(
            key.fingerprint(),
            AccountKey::from_bytes(1, [4u8; 32]).unwrap().fingerprint()
        );
        assert_ne!(
            key.fingerprint(),
            AccountKey::from_bytes(2, [3u8; 32]).unwrap().fingerprint()
        );
        assert_ne!(key.fingerprint()[..], key.items_key()[..16]);
    }

    #[test]
    fn rotation_increments_epoch() {
        let key = AccountKey::generate(&mut OsRng);
        let next = key.rotate(&mut OsRng);
        assert_eq!(next.epoch(), 2);
        assert_ne!(next.expose_secret(), key.expose_secret());
    }
}
