import AppKit

/// Writing to the general pasteboard. Images go out as PNG and TIFF, so every
/// app can paste them.
enum PasteboardWriter {
    static func write(text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    @discardableResult
    static func write(imageData data: Data) -> Bool {
        guard let rep = NSBitmapImageRep(data: data),
              let png = isPNG(data) ? data : rep.representation(using: .png, properties: [:]),
              let tiff = rep.tiffRepresentation
        else { return false }
        let pasteboard = NSPasteboard.general
        pasteboard.declareTypes([.png, .tiff], owner: nil)
        pasteboard.setData(png, forType: .png)
        pasteboard.setData(tiff, forType: .tiff)
        return true
    }

    static func isPNG(_ data: Data) -> Bool {
        data.starts(with: [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])
    }
}

/// Watches the pasteboard and saves every new copy to the history.
final class ClipboardWatcher {
    private let store: HistoryStore
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Content apps mark as not meant for a clipboard history (nspasteboard.org).
    private static let skippedTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]
    private static let imageExtensions: Set<String> = ["png", "jpg", "jpeg", "gif", "tif", "tiff", "bmp", "webp", "heic"]

    init(store: HistoryStore) {
        self.store = store
        // What's on the pasteboard now was copied before we started.
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.check()
        }
    }

    /// Call right after writing to the pasteboard, so that isn't saved as a
    /// new copy.
    func ignoreCurrentContents() {
        lastChangeCount = pasteboard.changeCount
    }

    private func check() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.skippedTypes) else { return }

        if let png = copiedImageFile() {
            store.addImage(png)
        } else if let text = pasteboard.string(forType: .string),
                  !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            store.addText(text)
        } else if let png = copiedImage() {
            store.addImage(png)
        }
    }

    /// An image copied as image data, as PNG.
    private func copiedImage() -> Data? {
        if let png = pasteboard.data(forType: .png) {
            return png
        }
        guard let tiff = pasteboard.data(forType: .tiff), let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    /// An image file copied in the Finder, as PNG.
    private func copiedImageFile() -> Data? {
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        guard let url = (pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL])?.first,
              Self.imageExtensions.contains(url.pathExtension.lowercased()),
              let data = try? Data(contentsOf: url)
        else { return nil }
        if PasteboardWriter.isPNG(data) {
            return data
        }
        return NSBitmapImageRep(data: data)?.representation(using: .png, properties: [:])
    }
}

/// `pastazzo-sync` drops items received from the other devices in the inbox.
/// This puts the newest on the pasteboard; the sync daemon has already added
/// them to the history.
final class InboxWatcher {
    private let directory: URL
    private let watcher: ClipboardWatcher
    private var source: DispatchSourceFileSystemObject?
    private var timer: Timer?

    init(directory: URL, watcher: ClipboardWatcher) {
        self.directory = directory
        self.watcher = watcher
    }

    func start() {
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let descriptor = open(directory.path, O_EVTONLY)
        if descriptor >= 0 {
            let source = DispatchSource.makeFileSystemObjectSource(fileDescriptor: descriptor, eventMask: .write, queue: .main)
            source.setEventHandler { [weak self] in self?.drain() }
            source.setCancelHandler { close(descriptor) }
            source.resume()
            self.source = source
        }
        // In case an event is missed.
        timer = Timer.scheduledTimer(withTimeInterval: 2, repeats: true) { [weak self] _ in
            self?.drain()
        }
        drain()
    }

    private func drain() {
        let files = FileManager.default
        guard let names = try? files.contentsOfDirectory(atPath: directory.path) else { return }
        let ready = names.filter { !$0.hasPrefix(".") }.sorted()
        guard let newest = ready.last else { return }
        for name in ready.dropLast() {
            try? files.removeItem(at: directory.appendingPathComponent(name))
        }

        let url = directory.appendingPathComponent(newest)
        defer { try? files.removeItem(at: url) }
        guard let data = try? Data(contentsOf: url) else { return }
        if url.pathExtension == "txt" {
            guard let text = String(data: data, encoding: .utf8) else { return }
            PasteboardWriter.write(text: text)
        } else if !PasteboardWriter.write(imageData: data) {
            return
        }
        watcher.ignoreCurrentContents()
    }
}
